### ISSUE TITLE
Settings parameter is ignored

### ISSUE THREAD

**Issue by grantemsley** [Distinqt/ZTIDellBIOSSettings#1]
The documentation says to use "/settings:"filename.cctk"

However, the code ignores the argument and only checks for the BIOSSettingsFile variable.  The argument is passed to Sub SetSettings as "Settingspath" on line 148, but Settingspath is never used.

Either the documentation needs to be updated, or SetSettings should check both the argument and the BIOSSettingsFile variable for a valid filename.

**Comment by NinoFloris** [comment]
You are absolutely correct. I will update the documentation. This was removed because it is redundant. Arguments can do the same "-i=##PATH_TO_SETTINGSFILE##", I will also mention this.
